# Generated by Django 2.2 on 2021-02-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ResizedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.MyFileModel', verbose_name='Оригинал')),
            ],
            options={
                'verbose_name': 'Измененный файл',
                'verbose_name_plural': 'Измененные файлы',
                'ordering': ['pk'],
            },
        ),
    ]
